# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]

  # 允许你从 Actions 选项卡手动运行此工作流程
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: |
        go build -o linux-tools main.go
      

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: latest
        token: ${{ secrets.TOEKN }}
        draft: false
        prerelease: false
        files: |
          linux-tools
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
